# ThanatosReports by Maximus Rossi
# Version: 1.0
# Permissions
# thanatosreports.report
# thanatosreports.report.exempt
# thanatosreports.reports.view
# thanatosreports.reports.delete
# thanatosreports.staffmessages
# Variables, %reportingPlayer%, %reportedPlayer%, %reason%, %ID%
Prefix: '&4&lThanatos&a&lReport '
List Format: '&aID:%ID% %reportingPlayer% &7reported &a%reportedPlayer% &7for &a%reason%'
Report Success: '&7You reported &a%reportedPlayer% &7for &a%reason%&7!'
Successful Delete: '&7Deleted report ID:&a%ID%&7!'
Successful DeleteALL: '&7Deleted all reports by &a%reportingPlayer%'
Reload Message: '&7Reloaded &aThanatosReports (V1.0)'
No Permission: '&4You do not have permission to use this command!'
Delete ID Error - 1: '&7Please enter a number.'
Cannot report yourself: '&7You cannot report yourself.'
Player was reported (Staff): '&a%reportingPlayer% &7has reported &a%reportedPlayer% &7for &a%reason%'
Cooldown Message: '&7Please wait &a%cooldown% seconds &7before reporting again!'
No Reports: '&7There are currently no reports.'
Cooldown Length: 240
Host: localhost
Port: 3306
Database: db
User: user
Password: pass
Table: ThanatosReports 
Options:
  Hacking:
    material: DIAMOND_SWORD
    displayname: '&4Hacking'
  Disrespect:
    material: FIREBALL
    displayname: '&5Disrespect'
