# ThanatosVoteParty by MaximusCarlos
# Version 1.1.0 | 07.02.2017
# thanatosvoteparty.admin
# thanatosvoteparty.open
# Alias = tvp
# %amount% %required% %player% %count%
# REQUIRE VOTE TO RECEIVE PARTY COMMAND IS PARTLY DISABLED RIGHT NOW AS IT'S NOT NEEDED, LEAVE AS FALSE
No Permission: '&4&lTVP &7No Permission'
Reload Message: '&4&lTVP &7Reloaded Config'
Reset Votes Message: '&4&lTVP &7Votes have been reset!'
Vote Count Set: '&4&lTVP &7Vote count set to &a%count%'
On Vote Message: '&e&l>> &eVoteparty! &a%amount% / %required%'
No Votes: '&e&l>> &eNo one has voted yet!'
Vote Party (All):
- '&8&l&m<------------------------------------------->'
- ''
- '&a&l%required% &evotes reached! You receive a reward!'
- ''
- '&8&l&m<------------------------------------------->'
Vote Party (Who Voted Only):
- '&8&l&m<------------------------------------------->'
- ''
- '&a&l%required% &evotes reached! You receive a reward!'
- '&7Only players who voted receive rewards!'
- ''
- '&8&l&m<------------------------------------------->'
Require vote to receive party command: false
Vote Count: 0
Votes Required: 50
Party Commands (Random Run):
  - scrates givekey EventCrate ALL 1
  - asa addmultiplier global 1.25 5
Party Commands (Always Run):
  - give %player% emeraldblock 192
